In [5]:
import numpy

world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",",dtype=str)
print(type(world_alcohol))
print(world_alcohol)
print(help(numpy.genfromtxt))

<type 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Para

In [17]:
import numpy
vector = numpy.array([1,2,3,4])
print(vector.shape)
matrix = numpy.array([[5,6,7],[12,34,23]])
print(matrix)
print(matrix.shape)
third = numpy.array([[[1,23,2],[4,5,6],[6,2,1]]])
print(third.shape)
print(third)
four = numpy.array([[[[1,23,2],[4,5,6],[6,2,1]]]])
print(four.shape)
print(four)

(4L,)
[[ 5  6  7]
 [12 34 23]]
(2L, 3L)
(1L, 3L, 3L)
[[[ 1 23  2]
  [ 4  5  6]
  [ 6  2  1]]]
(1L, 1L, 3L, 3L)
[[[[ 1 23  2]
   [ 4  5  6]
   [ 6  2  1]]]]


In [2]:
import numpy as np
world = np.genfromtxt("world_alcohol.txt", delimiter=",",dtype=str)
print world

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [3]:
other = world[1,3]
country = world[3,1]
print other, country

Wine Africa


In [11]:
print world[0:3,0:2]

[['Year' 'WHO region']
 ['1986' 'Western Pacific']
 ['1986' 'Americas']]


In [12]:
vector = np.array([5,10,15,20])
print vector[0:3]

[ 5 10 15]


In [18]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print matrix[:,0:2]
print matrix [:,2:4]

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [19]:
matrix == 6

array([[False, False, False],
       [False, False,  True],
       [False, False, False]], dtype=bool)

In [7]:
import numpy as np
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
two = (matrix==2)
three_or_ten = (matrix==3)|(matrix==10)
print matrix[two]
three_or_ten

[2]


array([[False, False,  True],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [17]:
import numpy as np
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print matrix.dtype
matrix = matrix.astype(float)
print matrix
print matrix.dtype
print matrix.min()
print matrix.max()
print matrix.sum(axis=1)
print matrix.sum(axis=0)

int32
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
float64
1.0
9.0
[  6.  15.  24.]
[ 12.  15.  18.]


In [22]:
import numpy as np
print np.arange(15).reshape(5,-1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [29]:
import numpy as np
print np.zeros((4,5))
print np.ones((4,5),dtype=int)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [30]:
import numpy as np
print np.arange(30,50,5)

[30 35 40 45]


In [36]:
import numpy as np
print np.random.random((4,5))
print np.linspace(0,34,100)

[[ 0.19414241  0.67465286  0.98071956  0.82193582  0.98876564]
 [ 0.92132355  0.63143924  0.04243565  0.4331208   0.99188258]
 [ 0.84076515  0.23375451  0.0340576   0.51261395  0.68584594]
 [ 0.09117394  0.64788544  0.69534091  0.90713483  0.819232  ]]
[  0.           0.34343434   0.68686869   1.03030303   1.37373737
   1.71717172   2.06060606   2.4040404    2.74747475   3.09090909
   3.43434343   3.77777778   4.12121212   4.46464646   4.80808081
   5.15151515   5.49494949   5.83838384   6.18181818   6.52525253
   6.86868687   7.21212121   7.55555556   7.8989899    8.24242424
   8.58585859   8.92929293   9.27272727   9.61616162   9.95959596
  10.3030303   10.64646465  10.98989899  11.33333333  11.67676768
  12.02020202  12.36363636  12.70707071  13.05050505  13.39393939
  13.73737374  14.08080808  14.42424242  14.76767677  15.11111111
  15.45454545  15.7979798   16.14141414  16.48484848  16.82828283
  17.17171717  17.51515152  17.85858586  18.2020202   18.54545455
  18.88888889  19.232

In [40]:
import numpy as np
a = np.array([1,2,3,4])
b = np.arange(4)
print a
print b
c = a-b
print c
print a<3
print a[a<3]

[1 2 3 4]
[0 1 2 3]
[1 1 1 1]
[ True  True False False]
[1 2]


In [43]:
import numpy as np
a = np.array([[2,3,4],
             [3,4,5],
             [5,6,7]])
b = np.array([[1,3,4],
             [7,4,3],
             [2,6,3]])
print a*b
print a.dot(b)

[[ 2  9 16]
 [21 16 15]
 [10 36 21]]
[[31 42 29]
 [41 55 39]
 [61 81 59]]


In [48]:
import numpy as np
a = np.arange(3)
print a
print np.exp(a)
print np.sqrt(a)

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [52]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
print a
print a.ravel()
print a.reshape(6,2)

[[ 5.  2.  7.  2.]
 [ 9.  1.  2.  2.]
 [ 7.  7.  5.  0.]]
[ 5.  2.  7.  2.  9.  1.  2.  2.  7.  7.  5.  0.]
[[ 5.  2.]
 [ 7.  2.]
 [ 9.  1.]
 [ 2.  2.]
 [ 7.  7.]
 [ 5.  0.]]


In [58]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
b = np.floor(10*np.random.random((3,4)))
print a
print b
print np.hstack((a,b))
print np.vstack((a,b))

[[ 1.  7.  8.  0.]
 [ 0.  9.  5.  6.]
 [ 9.  4.  9.  0.]]
[[ 7.  8.  5.  2.]
 [ 8.  7.  7.  8.]
 [ 0.  8.  3.  3.]]
[[ 1.  7.  8.  0.  7.  8.  5.  2.]
 [ 0.  9.  5.  6.  8.  7.  7.  8.]
 [ 9.  4.  9.  0.  0.  8.  3.  3.]]
[[ 1.  7.  8.  0.]
 [ 0.  9.  5.  6.]
 [ 9.  4.  9.  0.]
 [ 7.  8.  5.  2.]
 [ 8.  7.  7.  8.]
 [ 0.  8.  3.  3.]]


In [65]:
import numpy as np
a = np.floor(10*np.random.random((3,12)))
print a
#print np.hsplit(a,3)
#print np.vsplit(a,3)
print np.hsplit(a,(2,8))

[[ 0.  8.  3.  4.  5.  2.  4.  9.  0.  5.  3.  4.]
 [ 8.  7.  8.  7.  2.  2.  5.  6.  7.  2.  4.  5.]
 [ 3.  6.  5.  1.  9.  3.  8.  6.  6.  3.  3.  9.]]
[array([[ 0.,  8.],
       [ 8.,  7.],
       [ 3.,  6.]]), array([[ 3.,  4.,  5.,  2.,  4.,  9.],
       [ 8.,  7.,  2.,  2.,  5.,  6.],
       [ 5.,  1.,  9.,  3.,  8.,  6.]]), array([[ 0.,  5.,  3.,  4.],
       [ 7.,  2.,  4.,  5.],
       [ 6.,  3.,  3.,  9.]])]


In [71]:
import numpy as np
a = np.arange(12)
print a
b = a
print b is a
b.shape = 3,-1
print a
print id(a)
print id(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
110000848
110000848


In [77]:
c =a.view()
c.shape = 2,6
print a
print c
c[0,1] = 10
print a
print c

[[ 0 10  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0 10  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0 10  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0 10  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [84]:
d = a.copy()
d.shape = 2,6
print a
print d
d[0,1]=1
print a
print d

[[ 0 10  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0 10  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0 10  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [91]:
import numpy as np
data = np.sin(np.arange(20).reshape(5,4))
print data
index = data.argmax(axis=0)
print index
print range(data.shape[1])
data_max = data[index, range(data.shape[1])]
print data_max

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0, 1, 2, 3]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [95]:
import numpy as np
a = np.arange(0,40,10)
print a
b = np.tile(a, (10,3))
print b

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [111]:
import numpy as np
a = np.floor(np.random.random((3,4))*100)
print a
print np.sort(a,axis=1)
print np.argsort(a)

[[ 33.   9.  14.  89.]
 [ 25.  15.  25.  69.]
 [ 40.  80.  32.  98.]]
[[  9.  14.  33.  89.]
 [ 15.  25.  25.  69.]
 [ 32.  40.  80.  98.]]
[[1 2 0 3]
 [1 0 2 3]
 [2 0 1 3]]
